# Generated by Django 3.1.6 on 2021-02-05 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('rue', models.TextField()),
                ('numero', models.IntegerField()),
                ('ville', models.CharField(max_length=250)),
                ('pays', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('prix', models.FloatField()),
                ('dateentree', models.DateTimeField(auto_now_add=True)),
                ('datesortie', models.DateTimeField(blank=True, null=True)),
                ('dateconservation', models.DateTimeField()),
                ('quantite', models.IntegerField(null=True)),
                ('poids', models.CharField(max_length=100, null=True)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.fournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='TypeProduit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('unite_mesure', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreStock', models.IntegerField(null=True)),
                ('nombreVendu', models.IntegerField(null=True)),
                ('nombreSupprime', models.IntegerField(null=True)),
                ('nom_produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.produit')),
            ],
        ),
        migrations.AddField(
            model_name='produit',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.typeproduit'),
        ),
    ]
