# Generated by Django 3.1.6 on 2021-02-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Famille',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('nbrAdulte', models.IntegerField(default=1)),
                ('nbrEnfant', models.IntegerField(default=0)),
                ('nbrColis', models.IntegerField(default=0)),
                ('dateDernierColis', models.DateTimeField(blank=True, null=True)),
                ('composition', models.BooleanField()),
                ('date_cpas', models.DateTimeField(blank=True, null=True)),
                ('cpas_particulier', models.BooleanField()),
                ('pharmacie', models.BooleanField()),
                ('bus', models.BooleanField()),
                ('bte', models.BooleanField()),
            ],
        ),
    ]
