# Generated by Django 3.1.6 on 2021-02-16 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='famille',
            name='prenom',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
